language: cpp
dist: bionic

install: sudo apt-get install -y libsfml-dev libglew-dev

compiler:
    - gcc
    - clang
env:
    - BUILD_STATIC=True
    - BUILD_STATIC=False

matrix:
    exclude:
        compiler: clang
        env: BUILD_STATIC=True


before_script: mkdir build/ && cd build/
script:
    - cmake -DBUILD_STATIC=$BUILD_STATIC ..
    - make

after_success:
    - if [[ "$BUILD_STATIC" == "True" ]]; then wget -c https://raw.githubusercontent.com/probonopd/uploadtool/411ad0761033b4dd7bb5f4533b1be92c8216977b/upload.sh; fi
    - if [[ "$BUILD_STATIC" == "True" ]]; then bash upload.sh Fly; fi

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous.*)$/
